### ISSUE TITLE
Duplicate Ratgdo's Shown in HomeBridge UI

### ISSUE THREAD

**Issue by bverenkoff** [hjdhjd/homebridge-ratgdo#13]
### Homebridge Ratgdo

2.2.2

### Homebridge Platform and OS

Docker

### Homebridge Version

Ubuntu Focal (20.04.4 LTS)

### Node Version

20.15.0

### Ratgdo ESPHome Firmware Version

2024.5.5

### Describe the problem

I was running Ratgdo with ESPHome firmware fine for several months. I did OTA firmware update using the modified bin on your web site. After, I saw weird issues where only 1 of my 3 door openers would show up in HomeBridge. All 3 WebUIs would work. I reflashed all three using the Chrome flasher, and all three are working again.

However, in the HomeBridge UI, there are redundant versions of the RATGDO's, as if previous versions have been orphaned. I did full delete the HomeBridge plugin including config.

See attachment. When you select one, it groups all of the orphaned ones.

<img width="784" alt="Screenshot 2024-06-21 at 07 47 43" src="https://github.com/hjdhjd/homebridge-ratgdo/assets/68252613/d36b4dde-8fb8-4998-8f34-28641eb65c1e">

### Homebridge HBR JSON configuration

```json
{
    "name": "Ratgdo",
    "platform": "Ratgdo",
    "options": [
        "Disable.Motion",
        "Enable.Opener.Switch.RemoteLockout"
    ],
    "_bridge": {
        "username": "0E:8E:8C:77:B3:1E",
        "port": 35434
    }
}
```

### Relevant log output

```shell
N/A
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
You’ll need to delete the accessories from the Homebridge cache. You can do that in the Homebridge UI by going to its settings and going from there.

HBR will not delete an opener once it’s been discovered by design.

**Comment by bverenkoff** [comment]
Thanks, that worked. I had to remove them all, then re-add the plug-in, but it's all clean now.

Thanks!

**Comment by hjdhjd** [comment]
Glad it worked. I may change the way things work in the future, but while folks transition from the old world to the ESPHome world, it was the safer bet. 😄
