### ISSUE TITLE
ratgdov2.5i frequent timeout/reconnection

### ISSUE THREAD

**Issue by pdbennett** [hjdhjd/homebridge-ratgdo#14]
### Homebridge Ratgdo

2.2.2

### Homebridge Platform and OS

Docker on Unraid

### Homebridge Version

1.8.3

### Node Version

20.14.0

### Ratgdo ESPHome Firmware Version

2024.5.5

### Describe the problem

I am receiving frequent (once per min or so) time out/reconnect errors (log output attached). Door and light otherwise seem to be working, but sometimes with delay/lag. Enjoying experimenting with the hardware/plugin. Thanks for any help.

### Homebridge HBR JSON configuration

```json
{
    "name": "Ratgdo",
    "options": [
        "Disable.Motion",
        "Disable.Motion.D8BC3887D0FC"
    ],
    "_bridge": {
        "username": "0E:8D:DC:C6:88:5B",
        "port": 35209
    },
    "platform": "Ratgdo"
}
```

### Relevant log output

```shell
[6/23/2024, 2:16:39 PM] [Ratgdo] ratgdov2.5i 87d0fc: Connection to the Ratgdo controller has timed out while listening for events.
[6/23/2024, 2:16:39 PM] [Ratgdo] ratgdov2.5i 87d0fc: Unrecognized error: Event { message: undefined, type: 'error' }.
[6/23/2024, 2:17:16 PM] [Ratgdo] ratgdov2.5i 87d0fc: Ratgdo connected.
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
Glad you're enjoying it. The error is what it says it is...this isn't an HBR issue I'm afraid. The Ratgdo (or whatever device you're running Homebridge on) may be disconnecting and reconnecting to your WiFi would be my suspicion.

Not much I can do on this one...take a closer look at the connectivity situation and see where it leads?

**Comment by pdbennett** [comment]
Helpful - thanks!
