### ISSUE TITLE
Upgrade of ratgdo device causes an obstruction detected error

### ISSUE THREAD

**Issue by edrikk** [hjdhjd/homebridge-ratgdo#17]
### Homebridge Ratgdo

2.2.2 

### Homebridge Platform and OS

Docker in Debian

### Homebridge Version

v1.8.3 (Docker)

### Node Version

v20.15.0 

### Ratgdo ESPHome Firmware Version

v2024.* -- most recently experienced on upgrade to 2024.6.6

### Describe the problem

I've found the upgrading the ratgdo firmware (via esphome), after the ratgdo device reboots homekit shows status as obstruction detected.  
A restart of homebridge resolves the incorrect status.

### Homebridge HBR JSON configuration

```json
/
```

### Relevant log output

```shell
/
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by edrikk** [comment]
That was quick to go stale.

**Comment by hjdhjd** [comment]
Thanks for the report - not much for me to do with this one, but will see what I can observe on my end.
