### ISSUE TITLE
Update to documentation?

### ISSUE THREAD

**Issue by seanwalter** [hjdhjd/homebridge-ratgdo#19]
### Describe the feature request

I was facing an issue similar to #7 where after setup I was getting a nearly blank config screen, had no ability to create a child bridge, and my Ratgdo was not showing up in Homekit. I recommend updating the documentation to help avoid confusion if this comes up for others.

### Describe the proposed solution

I am not sure if all of the following are necessary, but these are the steps I took that finally brought up the full plugin config screen (which is amazing, btw...)

1. Reconnect Ratgdo to garage door opener (Up to this point I had been trying to get everything set up in Homebridge before going back out to my garage, and my Ratgdo was still plugged into my PC but accessible on wifi)

2. Perform the recommended door open/close to train the plugin on opening/closing times

3. Remove legacy garage door from the Homebridge cache

4. Install the Homebridge plugin, restart Homebridge

5. Go to the config screen, which will be mostly blank, wait a few to several seconds, and/or click Save (I am not sure if clicking Save on the blank screen is necessary, or if I just needed to wait several seconds for the plugin to find my device)

As I said above, I don't know which of the above steps are truly necessary for the plugin to detect the device and show the complete config screen. Possibly all users need to know is that they need to be patient on the "blank" config screen and wait for the plugin to discover the device.

In any case, being clear about that (or the need to click Save, or the need to go through some/all of those steps) would probably help others in the future. For my part, before doing the above I tried to troubleshoot by installing different ESPhome firmware versions and downgrading the plugin to different versions. I feel like I was lucky to have the idea of Saving the blank config screen, which either solved the problem or caused me to pause long enough for the plugin to find the device and bring up the full config screen.   

### Describe alternatives you have considered to the enhancement

I have not thought of other alternatives beyond what is probably a simple update to the documentation.

**Comment by hjdhjd** [comment]
Thanks for the suggestions…always looking for options to improve the onboarding experience.
