### ISSUE TITLE
Closing during mid open causes the garage door to get stuck

### ISSUE THREAD

**Issue by joshuafeldman** [hjdhjd/homebridge-ratgdo#21]
### Homebridge Ratgdo

v2.3.1

### Homebridge Platform and OS

Raspberry Pi

### Homebridge Version

v1.8.4

### Node Version

v20.12.2

### Ratgdo ESPHome Firmware Version

Latest

### Describe the problem

Sliding the control up to open the garage door works. If you slide it down to close before it has fully opened the garage door just gets stuck and does not actually close.

### Homebridge HBR JSON configuration

```json
{
    "name": "Ratgdo",
    "platform": "Ratgdo",
    "_bridge": {
        "username": "0E:65:32:7C:E8:58",
        "port": 30208
    }
}
```

### Relevant log output

```shell
[31/07/2024, 23:59:02] [Ratgdo] ratgdov2.5i eeab17: Opening.
[31/07/2024, 23:59:04] [Ratgdo] ratgdov2.5i eeab17: Stopped.
[31/07/2024, 23:59:12] [Ratgdo] ratgdov2.5i eeab17: Opening.
[31/07/2024, 23:59:13] [Ratgdo] ratgdov2.5i eeab17: Stopped.
[31/07/2024, 23:59:15] [Ratgdo] ratgdov2.5i eeab17: Opening.
[31/07/2024, 23:59:17] [Ratgdo] ratgdov2.5i eeab17: Stopped.
[31/07/2024, 23:59:18] [Ratgdo] ratgdov2.5i eeab17: Closing.
[31/07/2024, 23:59:23] [Ratgdo] ratgdov2.5i eeab17: Closed.
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
That's the intended function. If you interrupt an open or a close event, the door will stop. Working as designed.

**Comment by joshuafeldman** [comment]
@hjdhjd I understand what you are saying but I still advocate for this to be an issue and it isn't working as intended. Reason I say this is because in the UI the accessory control says "Closing..." but the state is stopped. As an end user you would have expected the garage door to stop opening and start closing. That control only has two states; opening and closing. So switching between the states should trigger those functions. There is no "stop" functionality here. Thoughts?

**Comment by hjdhjd** [comment]
It’s not an issue. The “Closing…” isn’t an HBR issue. Force-kill the Home app and see what it says. It’s a bug in the Home app…or you can look at another HomeKit app (Eve Home, Home+, etc.) and you’l also see state should be reported correctly.

If you interrupt an open or close cycle, the state will be stopped. I have no plans to revisit the design decision…a user should **not** be trying to flip between an open and a close event mid-cycle. If it is, it’s always an exception.
