### ISSUE TITLE
Add Friendly Name for Garage Doors and Gates

### ISSUE THREAD

**Issue by PaulDeas** [hjdhjd/homebridge-ratgdo#3]
### Describe the feature request

Right now, there doesn’t seem to be a way, within HomeBridge, to name each RATGDO device.  I have many and I have to keep track of them by names like ratgdov25i-xxxxxxx.  Writhin Homekit, I can rename then, of course, but within HomeBridge, it is just a bit more difficult to figure out which door I am dealing with.  

### Describe the proposed solution

Add a feature option for each GDO something like

name.xxxxxxxxx = 

### Describe alternatives you have considered to the enhancement

Alternatively, I think the name might be coming from the RATGDO itself. But within ESPHOME firmware download, there doesn’t seem to be a place to change the name.

**Comment by DMBlakeley** [comment]
Within Homebridge, if you go to the Accessories tab and then select the Settings gear on the tile for the Garage door, you can rename as desired.

**Comment by hjdhjd** [comment]
This already exists. Just rename away within the Home app… 😄 

Alternatively, two ways to distinguish:

1. Upload your own custom YAML to your various Ratgdos…
2. Look at the information detail of each garage door opener and pay attention to the serial number - it will be the MAC address of a given Ratgdo device. You can map them back that way as well.

Enjoy.

**Comment by PaulDeas** [comment]
Although I can rename the accessory, it still shows up here with the original names:

***@***.***


From: hjdhjd ***@***.***>
Date: Sunday, May 5, 2024 at 1:39 PM
To: hjdhjd/homebridge-ratgdo ***@***.***>
Cc: Paul Deas ***@***.***>, Author ***@***.***>
Subject: Re: [hjdhjd/homebridge-ratgdo] Add Friendly Name for Garage Doors and Gates (Issue #3)

This already exists. Just rename away within the Home app… 😄

Enjoy.
