### ISSUE TITLE
HBR Must Be Configured and Started in Homebridge Before Autodiscovery Will Work

### ISSUE THREAD

**Issue by pwrmiller** [hjdhjd/homebridge-ratgdo#5]
### Homebridge Ratgdo

2.1.3

### Homebridge Platform and OS

Debian 11

### Homebridge Version

1.8.1

### Node Version

20.12.2

### Ratgdo ESPHome Firmware Version

ratgdov2.5i 1ba3e5

### Describe the problem

This plugin doesn't autodetect GDOs until clicking (in homebridge) Plugins > Plugin Config > Save. 

Interestingly, the plugin configuration settings don't even show up until saving the configuration (just showing the HomeBridge and RATGDO logo and close, trash, and save buttons) without the SETTINGS/ FEATURE OPTIONS/ SUPPORT tabs. 

Before attempting this, I updated all components (incl. node, homebridge, ui, etc) several times. The only thing getting the plugin to work was clicking the SAVE button in its Config (e.g. saving nothing).

The logs indicate that only one platform is loaded despite the homebridge-ratgdo.Ratdgo platform being registered. Seems to be in a partially set up state until SAVE is clicked.

I appreciate your hard work on this plugin and integration. Let me know if there's any additional information you need - I'd be happy to provide. Since this seems to be resolved, you can mark it as complete, but I thought recording this information for posterity would be useful for others experiencing the same issue.

### Homebridge HBR JSON configuration

```json
{
    "bridge": {
        "name": "Homebridge Something",
        "username": "some:mac:address",
        "port": 51930,
        "pin": "123-45-1234",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Ratgdo",
            "platform": "Ratgdo"
        }
    ],
    "disabledPlugins": []
}
```

### Relevant log output

```shell
[5/7/2024, 8:45:47 AM] ---
[5/7/2024, 8:45:48 AM] Loaded plugin: homebridge-config-ui-x@4.56.2
[5/7/2024, 8:45:48 AM] Registering platform 'homebridge-config-ui-x.config'
[5/7/2024, 8:45:48 AM] ---
[5/7/2024, 8:45:49 AM] Loaded plugin: homebridge-ratgdo@2.1.3
[5/7/2024, 8:45:49 AM] Registering platform 'homebridge-ratgdo.Ratgdo'
[5/7/2024, 8:45:49 AM] ---
[5/7/2024, 8:45:49 AM] Loading 1 platform
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
You’re correct - the plugin needs to be instantiated at least once. :smile: I’ll refine the documentation a bit more in future versions to make it more clear to new users. Thanks. 😄
