### ISSUE TITLE
Set up screen not loading in config-ui-x (JS error)

### ISSUE THREAD

**Issue by jarz** [hjdhjd/homebridge-ratgdo#8]
### Homebridge Ratgdo

v2.1.3

### Homebridge Platform and OS

Docker

### Homebridge Version

v1.8.2

### Node Version

v20.12.2

### Ratgdo ESPHome Firmware Version

v2024.5.0

### Describe the problem

Attempting to set up _homebridge-ratgdo_ for the first time.

After installing the plugin and clicking the _Set up_ button, not much happens.
<img width="827" alt="image" src="https://github.com/hjdhjd/homebridge-ratgdo/assets/90255/f325a78d-c9c8-4ebd-b8b3-938e5603fcc5">

Here's what's logged in the console:
```
TypeError: Cannot set properties of null (setting 'innerHTML')
    at showFirstRun (VM7678 ui.mjs:18:28)
    at launchWebUI (VM7678 ui.mjs:129:3)
```

[Line](https://github.com/hjdhjd/homebridge-ratgdo/blob/9759c83dc5e206b07d5f1cce3c7510b5361a088c/homebridge-ui/public/ui.mjs#L18)

### Homebridge HBR JSON configuration

```json
{
    "platform": "Ratgdo",
    "name": "Ratgdo"
}
```

### Relevant log output

```shell
None
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
Hey Tim. Been a minute!

Have you checked to verify you don't have ad blockers, etc running? I just tried a clean, vanilla setup and it runs fine - and haven't had anyone raise any issues on the webUI since the plugin launched a number of months ago.. Thoughts?

**Comment by hjdhjd** [comment]
> Hey Tim. Been a minute!
> 
> Have you checked to verify you don't have ad blockers, etc running? I just tried a clean, vanilla setup and it runs fine - and haven't had anyone raise any issues on the webUI since the plugin launched a number of months ago.. Thoughts?

Addressed in the next release...thanks.
